volumes:
  minio:
  postgres:
    driver: local

secrets:
  service-account-key:
    file: ./service_account_key.json

services:
 minio:
   image: minio/minio
   volumes:
     - minio:/data
   ports:
     - "9000:9000"
     - "9001:9001"
   env_file:
     - .env
   environment:
     MINIO_ROOT_USER: minio
   command: server /data --console-address ":9001"
   healthcheck:
     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
     interval: 30s
     timeout: 20s
     retries: 3

 createbucket:
   image: minio/mc
   depends_on:
     - minio
   env_file:
     - .env
   entrypoint: >
     /bin/sh -c "
     sleep 5;
     /usr/bin/mc config host add myminio http://minio:9000 minio ${MINIO_ROOT_PASSWORD};
     /usr/bin/mc mb myminio/${S3_BUCKET_NAME};
     /usr/bin/mc anonymous set public myminio/${S3_BUCKET_NAME};
     exit 0;
     "

 postgres:
   restart: always
   image: postgres:17.4
   environment:
     POSTGRES_USER: openoversight
     POSTGRES_PASSWORD: terriblepassword
     POSTGRES_DB: openoversight-dev
   volumes:
     - postgres:/var/lib/postgresql/data
   ports:
     - "5432:5432"

 web:
   restart: always
   build:
      context: .
      dockerfile: dockerfiles/web/Dockerfile-dev
   depends_on:
     - postgres
     - minio
   env_file:
     - .env
   environment:
     APPROVE_REGISTRATIONS: "${APPROVE_REGISTRATIONS}"
     ENV: "development"
     FLASK_APP: OpenOversight.app
     FLASK_DEBUG: 1
     OO_HELP_EMAIL: "info@lucyparsonslabs.com"
     OO_SERVICE_EMAIL: "openoversightchi@lucyparsonslabs.com"
     # Update with your application's respective Olson-style timezone:
     # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#list
     TIMEZONE: "America/Chicago"
   volumes:
     - ./OpenOversight/:/usr/src/app/OpenOversight/:z
   secrets:
     - source: service-account-key
       target: /usr/src/app/service_account_key.json
   user: "${UID:?Docker-compose needs UID set to the current user id number. Try 'export UID' and run docker compose again}"
   links:
     - postgres:postgres
   expose:
     - "3000"
   ports:
     - "3000:3000"

 web-test:
   restart: always
   build:
     context: .
     args:
       - MAKE_PYTHON_VERSION
     dockerfile: dockerfiles/web/Dockerfile-test
   depends_on:
     - createbucket
   env_file:
     - .env
   environment:
     ENV: "testing"
     FLASK_APP: OpenOversight.app
     OO_HELP_EMAIL: "info@lucyparsonslabs.com"
     OO_SERVICE_EMAIL: "openoversightchi@lucyparsonslabs.com"
     TIMEZONE: "America/Chicago"
   volumes:
     - ./:/usr/src/app:z
