FROM python:3.11-bullseye

WORKDIR /usr/src/app

ENV CURL_FLAGS="--proto =https --tlsv1.2 -sSf -L --max-redirs 1 -O"

ENV DEBIAN_FRONTEND=noninteractive
ENV DISPLAY=:1
ENV PYTHONDONTWRITEBYTECODE=1

# install apt dependencies
RUN apt-get update && apt-get install -y xvfb libpq-dev python3-dev graphviz-dev graphviz && \
    apt-get clean

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# Add uv to PATH
ENV PATH="/root/.local/bin:$PATH"

COPY requirements.txt /usr/src/app/

RUN uv pip install --system -r requirements.txt

COPY create_db.py test_data.py /usr/src/app/

ENV SECRET_KEY 4Q6ZaQQdiqtmvZaxP1If
ENV SQLALCHEMY_DATABASE_URI postgresql://openoversight:terriblepassword@postgres/openoversight-dev

WORKDIR /usr/src/app/

CMD ["OpenOversight/scripts/entrypoint_dev.sh"]
