ARG MAKE_PYTHON_VERSION
FROM python:${MAKE_PYTHON_VERSION:-3.11}-bullseye

WORKDIR /usr/src/app

ENV CURL_FLAGS="--proto =https --tlsv1.2 -sSf -L --max-redirs 1 -O"

ENV DEBIAN-FRONTEND noninteractive
ENV PYTHONDONTWRITEBYTECODE=1

# install apt dependencies
RUN apt-get update && apt-get install -y curl libpq-dev python3-dev && \
    apt-get install -y libsqlite3-0 graphviz-dev graphviz && apt-get clean

COPY requirements.txt dev-requirements.txt /usr/src/app/
# install rust and cargo so we can use jellyfish
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y && \
    . "$HOME/.cargo/env" && \
    pip3 install --no-cache-dir -r requirements.txt && \
    pip3 install --no-cache-dir -r dev-requirements.txt

RUN playwright install --with-deps chromium

COPY ./scripts/create_db.py ./scripts/test_data.py /usr/src/app/

ENV SECRET_KEY 4Q6ZaQQdiqtmvZaxP1If

WORKDIR /usr/src/app/
