import os


# Cache Key Constants
KEY_DEPT_ASSIGNMENTS_LAST_UPDATED = "assignments_last_updated"
KEY_DEPT_INCIDENTS_LAST_UPDATED = "incidents_last_updated"
KEY_DEPT_OFFICERS_LAST_UPDATED = "officers_last_updated"

# Database Key Constants
KEY_DB_CREATOR = "creator"

# Config Key Constants
KEY_ALLOWED_EXTENSIONS = "ALLOWED_EXTENSIONS"
KEY_DATABASE_URI = "SQLALCHEMY_DATABASE_URI"
KEY_ENV = "ENV"
KEY_ENV_DEV = "development"
KEY_ENV_TESTING = "testing"
KEY_ENV_PROD = "production"
KEY_NUM_OFFICERS = "NUM_OFFICERS"
KEY_OFFICERS_PER_PAGE = "OFFICERS_PER_PAGE"
KEY_OO_MAIL_SUBJECT_PREFIX = "OO_MAIL_SUBJECT_PREFIX"
KEY_OO_HELP_EMAIL = "OO_HELP_EMAIL"
KEY_OO_SERVICE_EMAIL = "OO_SERVICE_EMAIL"
KEY_MAIL_SERVER = "MAIL_SERVER"
KEY_MAIL_PORT = "MAIL_PORT"
KEY_MAIL_USE_TLS = "MAIL_USE_TLS"
KEY_MAIL_USERNAME = "MAIL_USERNAME"
KEY_MAIL_PASSWORD = "MAIL_PASSWORD"
KEY_S3_BUCKET_NAME = "S3_BUCKET_NAME"
KEY_TIMEZONE = "TIMEZONE"

# File Handling Constants
ENCODING_UTF_8 = "utf-8"
FILE_TYPE_HTML = "html"
FILE_TYPE_PLAIN = "plain"
SAVED_UMASK = os.umask(0o077)  # Ensure the file is read/write by the creator only

# File Name Constants
SERVICE_ACCOUNT_FILE = "service_account_key.json"

# Key Constants
KEY_OFFICERS_PER_PAGE = "OFFICERS_PER_PAGE"
KEY_TIMEZONE = "TIMEZONE"

# Numerical Constants
BYTE = 1
KILOBYTE = 1024 * BYTE
MEGABYTE = 1024 * KILOBYTE
MINUTE = 60
HOUR = 60 * MINUTE

# Test Constants
ADMIN_EMAIL = "test@example.org"
ADMIN_PASSWORD = "testtest"
