"""Add ranks table

Revision ID: 117fa0e07387
Revises: 2a9064a2507c
Create Date: 2019-01-09 20:26:58.960113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117fa0e07387'
down_revision = '2a9064a2507c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'ranks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('rank', sa.String(length=255), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('department_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ranks_order'), 'ranks', ['order'], unique=False)
    op.create_index(op.f('ix_ranks_rank'), 'ranks', ['rank'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ranks_rank'), table_name='ranks')
    op.drop_index(op.f('ix_ranks_order'), table_name='ranks')
    op.drop_table('ranks')
    # ### end Alembic commands ###
