"""empty message
Revision ID: 19f23f6eb170
Revises: af933dc1ef93
Create Date: 2018-05-06 12:55:02.139610
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '19f23f6eb170'
down_revision = 'af933dc1ef93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'start_no',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=120),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'start_no',
                    existing_type=sa.String(length=120),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    # ### end Alembic commands ###
