"""add occurred_at to incidents

Revision ID: 2b99be2696a9
Revises: b38c133bed3c
Create Date: 2023-08-07 21:14:31.711553

"""
import os

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2b99be2696a9'
down_revision = 'b38c133bed3c'
branch_labels = None
depends_on = None


TIMEZONE = os.getenv("TIMEZONE", "America/Chicago")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_incidents_occurred_at'), ['occurred_at'], unique=False)

    op.execute(
        f"""
            UPDATE incidents
            SET occurred_at = (date::date || ' ' || time::timetz)::timestamp AT TIME ZONE '{TIMEZONE}'
            WHERE occurred_at IS NULL
            AND time IS NOT NULL
            AND date IS NOT NULL
        """
    )

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_incidents_occurred_at'))
        batch_op.create_index('ix_incidents_time', ['time'], unique=False)

    op.execute(
        f"""
            UPDATE incidents
            SET (date, time) = (occurred_at::date, (occurred_at::timestamptz AT TIME ZONE '{TIMEZONE}')::time)
            WHERE occurred_at IS NOT NULL
            """
    )

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_column('occurred_at')

    # ### end Alembic commands ###
