"""add state column to departments

Revision ID: bce7c55b6d90
Revises: 1931b987ce0d
Create Date: 2023-07-25 21:22:48.935645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce7c55b6d90'
down_revision = '1931b987ce0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=2)))
        batch_op.drop_index('ix_departments_name')
        batch_op.create_unique_constraint('departments_name_state', ['name', 'state'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('departments_name_state', type_='unique')
        batch_op.create_index('ix_departments_name', ['name'], unique=True)
        batch_op.drop_column('state')

    # ### end Alembic commands ###
