"""add state to department

Revision ID: eb854f312a3a
Revises: 1931b987ce0d
Create Date: 2023-07-21 20:58:22.178784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb854f312a3a'
down_revision = '1931b987ce0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_departments_state'), ['state'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_state'))
        batch_op.drop_column('state')

    # ### end Alembic commands ###
