"""modify departments for creating and editing

Revision ID: 6c174378a47e
Revises: eb854f312a3a
Create Date: 2023-07-24 21:29:05.279032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c174378a47e'
down_revision = 'eb854f312a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index('ix_departments_name')
        batch_op.create_unique_constraint('departments_name_state', ['name', 'state'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('departments_name_state', type_='unique')
        batch_op.create_index('ix_departments_name', ['name'], unique=True)

    # ### end Alembic commands ###
