"""add created_at columns

Revision ID: 6c5f7d554e5e
Revises: 18f43ac4622f
Create Date: 2023-08-01 16:34:56.541227

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "6c5f7d554e5e"
down_revision = "18f43ac4622f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assignments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("faces", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("incident_license_plates", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("incident_links", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("incident_officers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("license_plates", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("links", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("officer_incidents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("officer_links", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("officers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("salaries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("unit_types", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("unit_types", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("salaries", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("officers", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("officer_links", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("officer_incidents", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("links", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("license_plates", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("incidents", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("incident_officers", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("incident_links", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("incident_license_plates", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("faces", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("departments", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    with op.batch_alter_table("assignments", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
