"""rename 'star_date'

Revision ID: 33521389a38d
Revises: 93fc3e074dcc
Create Date: 2023-07-18 16:16:11.847465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33521389a38d'
down_revision = '93fc3e074dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.drop_index('ix_assignments_star_date')
        batch_op.create_index(batch_op.f('ix_assignments_start_date'), ['start_date'], unique=False)
        batch_op.drop_column('star_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('star_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_assignments_start_date'))
        batch_op.create_index('ix_assignments_star_date', ['star_date'], unique=False)
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
