"""add facial_recognition_allowed field to departments table

Revision ID: 351a3118fc6b
Revises: 8ce3de7679c2
Create Date: 2019-07-07 17:38:06.119009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351a3118fc6b'
down_revision = '8ce3de7679c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('facial_recognition_allowed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'facial_recognition_allowed')
    # ### end Alembic commands ###
