"""Adds sorted_by_rekognition field to raw_images table

Revision ID: 4f5033b3a141
Revises: 351a3118fc6b
Create Date: 2019-08-11 19:32:41.433463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5033b3a141'
down_revision = '351a3118fc6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_images', sa.Column('sorted_by_rekognition', sa.Boolean(), default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_images', 'sorted_by_rekognition')
    # ### end Alembic commands ###
