"""Refactor links

Revision ID: 86eb228e4bc0
Revises: 2a9064a2507c
Create Date: 2019-03-15 22:40:10.473917

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '86eb228e4bc0'
down_revision = '2a9064a2507c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('links_user_id_fkey', 'links', type_='foreignkey')
    op.alter_column('links', 'user_id', new_column_name='creator_id')
    op.create_foreign_key(None, 'links', 'users', ['creator_id'], ['id'], ondelete='SET NULL')
    op.add_column('links', sa.Column('officer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'links', 'officers', ['officer_id'], ['id'], ondelete='CASCADE')
    op.execute('UPDATE links SET officer_id = officer_links.officer_id FROM officer_links WHERE officer_links.link_id = links.id')
    op.drop_table('officer_links')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'officer_links',
        sa.Column('officer_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column('link_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['link_id'], ['links.id'], name='officer_links_link_id_fkey'),
        sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], name='officer_links_officer_id_fkey'),
        sa.PrimaryKeyConstraint('officer_id', 'link_id', name='officer_links_pkey'))
    op.drop_constraint('links_creator_id_fkey', 'links', type_='foreignkey')
    op.drop_constraint('links_officer_id_fkey', 'links', type_='foreignkey')
    op.alter_column('links', 'creator_id', new_column_name='user_id')
    op.create_foreign_key('links_user_id_fkey', 'links', 'users', ['user_id'], ['id'])
    op.execute('INSERT INTO officer_links (officer_id, link_id) SELECT officer_id, id FROM links')
    op.drop_column('links', 'officer_id')
    # ### end Alembic commands ###
