"""empty message

Revision ID: 8ce3de7679c2
Revises: 770ed51b4e16
Create Date: 2019-04-17 18:26:35.733783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ce3de7679c2'
down_revision = '770ed51b4e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('unique_internal_identifier_label', sa.String(length=100), nullable=True))
    op.drop_column('departments', 'uii')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('uii', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('departments', 'unique_internal_identifier_label')
    # ### end Alembic commands ###
