"""empty message

Revision ID: 8d8769c3ecc6
Revises: 8ce7926aa132
Create Date: 2018-07-02 01:51:06.750736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8769c3ecc6'
down_revision = '8ce7926aa132'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'detected_faces',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('img_id', sa.Integer(), nullable=True),
        sa.Column('face_top', sa.Float(), nullable=True),
        sa.Column('face_left', sa.Float(), nullable=True),
        sa.Column('face_width', sa.Float(), nullable=True),
        sa.Column('face_height', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['img_id'], ['raw_images.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detected_faces')
    # ### end Alembic commands ###
