"""Remove character limit of url field in link model.

Revision ID: 93fc3e074dcc
Revises: cd39b33b5360
Create Date: 2022-01-05 06:50:40.070530

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "93fc3e074dcc"
down_revision = "cd39b33b5360"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "links",
        "url",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "links",
        "url",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
