"""empty message

Revision ID: ae976537abfd
Revises: b883b2c9f239
Create Date: 2018-08-16 02:21:50.958467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae976537abfd'
down_revision = 'b883b2c9f239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('supervisor_star_no', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_assignments_supervisor_star_no'), 'assignments', ['supervisor_star_no'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_supervisor_star_no'), table_name='assignments')
    op.drop_column('assignments', 'supervisor_star_no')
    # ### end Alembic commands ###
