"""Add unique constraint to officer full name; add suffix to officer

Revision ID: b883b2c9f239
Revises: 7bb53dee8ac9
Create Date: 2018-07-31 15:21:42.941601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b883b2c9f239'
down_revision = '7bb53dee8ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', sa.Column('suffix', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_officers_suffix'), 'officers', ['suffix'], unique=False)
    op.create_unique_constraint(None, 'officers', ['first_name', 'middle_initial', 'last_name', 'suffix'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'officers', type_='unique')
    op.drop_index(op.f('ix_officers_suffix'), table_name='officers')
    op.drop_column('officers', 'suffix')
    # ### end Alembic commands ###
