"""add uii string column to departments table

Revision ID: bde5faf0270c
Revises: 2a9064a2507c
Create Date: 2019-03-28 14:04:58.696848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde5faf0270c'
down_revision = '2a9064a2507c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('uii', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'uii')
    # ### end Alembic commands ###
