"""empty message

Revision ID: ca95c047bf42
Revises: 6065d7cdcbf8
Create Date: 2018-05-10 20:02:19.006081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca95c047bf42'
down_revision = '6065d7cdcbf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('department_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incidents', 'departments', ['department_id'], ['id'])
    op.drop_index('ix_license_plates_non_state_identifier', table_name='license_plates')
    op.drop_column('license_plates', 'non_state_identifier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('license_plates', sa.Column('non_state_identifier', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.create_index('ix_license_plates_non_state_identifier', 'license_plates', ['non_state_identifier'], unique=False)
    op.drop_constraint(None, 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'department_id')
    # ### end Alembic commands ###
