"""constrain officer gender options

Revision ID: cd39b33b5360
Revises: 562bd5f1bc1f
Create Date: 2020-07-13 02:45:07.533549

"""
from alembic import op
import sqlalchemy as sa
from exceptions import NotImplementedError


# revision identifiers, used by Alembic.
revision = 'cd39b33b5360'
down_revision = '562bd5f1bc1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    raise NotImplementedError(
        "need to normalize the gender options first, using update queries"
    )
    op.alter_column('officers', 'gender',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=5),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('officers', 'gender',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###
