corrections = {
    "Harbor - Squad D": ("Harbor    Squad D",),
    "Harbor - Squad C": ("'Harbor - Squad C",),
    "Parking Enforcement - P6 Squad": (". Parking Enforcement - P6 Squad",),
    "Parking Enforcement - P1 Squad": ("Parking Enforcement    P1 Squad",),
    "Parking Enforcement - P7 Squad": ("Parking Enforcement    P7 Squad",),
    "Parking Enforcement - P3 Squad": ("Parking Enforcement -, P3 Squad",),
    "North Pct 2Nd W - Nora": (
        "North Pct 2Nd W    Nora",
        "North Pet 2Nd W - Nora",
        "North Pot 2Nd W - Nora",
    ),
    "East Pct 2Nd W - Beats": (
        "East Pct 2Nd W    Beats",
        "East Pet 2Nd W - Beats",
    ),
    "West Pct 2Nd W - Mary Beats": (
        "West Pct 2Nd W Mary Beats",
        "West Pot 2Nd W - Mary Beats",
    ),
    "West Pct 2Nd W - David Beats": ("West Pat 2Nd W - David Beats",),
    "West Pct 3Rd W - David Beats": ("West Pot 3Rd W - David Beats",),
    "North Pct 2Nd W - Nw": ("2 North Pct 2Nd W - Nw",),
    "North Pct 3Rd W - Nw": ("3 North Pct 3Rd W - Nw",),
    "Administrative Services - Administration": (
        "Administrative Services - Administra",
        "Administrative Services - Administ~",
    ),
    "Advanced Training - A": ("Advanced Training -A",),
    "Advanced Training - B": ("Advanced Training - Squad B",),
    "Afis Administration Unit": ("Afis Administration",),
    "Apr - Audit, Policy And Research S": ("Apr - Audit, Policy And Research S~",),
    "Apr - Policy And Procedures Detail": (
        "Apr - Policy And Procedures",
        "Apr - Policy And Procedure Detail",
    ),
    "Arson/Bomb - Squad B": ("Arson/Bomb - Squad 'B",),
    "Budget And Finance Administration": (
        "Budget & Finance Administration",
        "Budget And Finance Administation",
        "Budget And Finance",
    ),
    "Budget and Finance - Facilities Coordinator": (
        "Budget And Finance - Facilities Coo",
        "Budget And Finance - Facilities Co~",
    ),
    "Cci - General Investigations Squad": ("Cci - General Investigations Squad~",),
    "Cci - General Investigations Unit": ("Cci - General Investigations Unit ~",),
    "Narc - General Investigations Unit": (
        "Narc - General Investigations Unit -",
        "Narc - General Investigations Unit - Admin",
        "Narc - General Investigations Unit~",
        "Narc - General Investigations - Ad~",
    ),
    "Vice - General Investigations Squad": (
        "Vice -  General Investigations Squad",
        "Vice - General Investigations Squa~",
        "Vice General Investigations Squad",
    ),
    "Chief Administrative Officer": ("Chief Administrative Officer - Admi",),
    "Chief Strategy Officer - Administration": (
        "Chief Strategy Officer - Administrati",
        "Chief Strategy Officer - Administr~",
    ),
    "Collaborative Policing Bureau - Administration": (
        "Collaborative Policing Bureau",
        "Collaborative Policing Bureau - Adm",
        "Collaborative Policing Bureau - Ad~",
        "Collaborative Policing Section - A~",
    ),
    "Comm - 1St W": ("Comm 1St W",),
    "Comm - 3Rd W": ("Comm -'3Rd W", "Comm 3Rd W", "Comm'- 3Rd W"),
    "Comm - 5Th W": ("Comm 5Th VV", "Comm 5Th W"),
    "Comm - Administration Management": ("Comm - Administration Managemen",),
    "Comm - Floor Operations Management": ("Comm - Floor Operations Managem",),
    "Comm - Internet And Telephone Rep": ("Comm - Internet And Telephone Repo~",),
    "Comm - Training": ("Comm - Training Detail", "Comm Training"),
    "Comm - Training And Performance Management": (
        "Comm - Training And Performance M",
        "Comm - Training And Performance Ma~",
    ),
    "Comm Ops/Trng - Unavail Personnel": ("Comm Ops/Trng - Unavail Personr",),
    "Communications Section - Administration": (
        "Communications Section - Adminis",
        "Communications Section - Administr~",
    ),
    "Community Outreach - Crime Prevention": (
        "Community Outreach -  Crimestoppers",
        "Community Outreach - Crime Preve",
        "Community Outreach - Crime Prevent~",
        "Community Outreach - Crime Stopp",
    ),
    "Community Outreach - False Alarm": (
        "Community Outreach - False Alarm Detail",
        "Community Outreach - False Alarm D~",
    ),
    "Community Outreach - Outreach Squad": (
        "Community Outreach - Outreach Sq",
        "Community Outreach - Outreach Squa~",
    ),
    "Community Outreach - Special Projects Detail": (
        "Community Outreach - Special Proj",
    ),
    "Community Outreach - Youth Violence": (
        "Community Outreach - Youth Violen",
        "Community Outreach - Youth Violenc~",
        "Community Outreach And Youth Violence Unit",
    ),
    "Coo - Chief Operating Officer - Administration": (
        "Coo - Chief Operating Officer",
        "Coo - Chief Operating Officer - Adm",
        "Coo - Chief Operating Officer - Ad~",
    ),
    "Coo - Special Assignment": ("Cop - Special Assignment",),
    "Intell - Special Assignments": ("Intel) - Special Assignments",),
    "Coordinated Crim Inv Section - Administration": (
        "Coordinated Crim Inv Section - Adm",
        "Coordinated Crim Inv Section - Adm~",
    ),
    "Coordinated Criminal Investigations": (
        "Coordinated Criminal Investigations Section",
        "Coordinated Criminal Investigation~",
    ),
    "Legal - Senior Police Counsel": (
        "Legal - Senior Police Counsel - Adm",
        "Legal - Senior Police Counsel - Ad~",
    ),
    "Cop - Strategic Communications": (
        "Cop - Strategic Communications - M~",
        "Cop - Strategic Communications - P~",
    ),
    "Criminal History - Juvenile Records": ("Criminal History - Juvenile Record~",),
    "Crisis Intervention And Response Unit": (
        "Crisis Intervention And Response U",
        "Crisis Intervention Response Team",
    ),
    "Crisis Intervention Coordination Squad": (
        "Crisis Intervention Coordination Squ",
        "Crisis Intervention Coordination S~",
    ),
    "Data Driven - Analysts": ("Data Driven Analysts",),
    "Deputy Chief Of Staff - Administration": ("Deputy Chief Of Staff - Administrat",),
    "Deputy Chief Operations - Administration": (
        "Deputy Chief Operations - Administ",
        "Deputy Chief Operations - Administ~",
    ),
    "Dv - Domestic Violence Unit - Administration": (
        "Dv - Domestic Violence Unit - Admi",
        "Dv - Domestic Violence Unit - Admi~",
        "Domestic Violence Unit - Administr",
        "Domestic Violence Unit - Administration",
    ),
    "Vst - Victim Support Team": ("Dv - Vst (Victim Support Team)",),
    "Dv Squad C - Elder Abuse & Fraud": ("Dv Squad C - Elder Abuse & Frauc",),
    "East Pct 1St W - Pct Support": ("East Pct 1St W    Pct Support",),
    "North Pct 1St W - Pct Support": ("North Pct 1St W    Pct Support",),
    "East Pct 2Nd W - Charlie": ("East Pct 2Nd W    Charlie",),
    "East Pct 3Rd W - Charlie": (
        "East Pct 3Rd VV - Charlie",
        "East Pct 3Rd W - Charlie �",
        "East Pct 3Rd W- Charlie",
        "East Pct 3rd  W - Charlie",
    ),
    "East Pct 1St W - Charlie": ("East Pet 1St W- Charlie",),
    "East Pct 2Nd W - Edward": (
        "East Pct 2Nd W -'Edward",
        "East Pot 2Nd W - Edward",
    ),
    "East Pct 2Nd W - George": ("East Pct wnd W - George",),
    "East Pct 1St W - E/G Relief (Charlie)": (
        "East Pct 1St W - E/G Relief (Charli",
        "East Pct 1St W - E/G Relief (Charl~",
    ),
    "East Pct 3Rd W - Edward": ("East Pet 3Rd W    Edward",),
    "East Pct 3Rd W - George": ("East Pet 3Rd W - George",),
    "East Pct 1St W - George": (
        "East Pct 1St W- George",
        "East Pot 1St W'- George",
        "East Pot 1St W - George",
    ),
    "West Pct 3Rd W - Pct Support": ("West Pct 3Rd W    Pct Support",),
    "East Pct 1St W - Unavail Personnel": (
        "East Pct 1St W - Unavail PersonnE",
        "East Pct 1St W - Unavail Personn�",
        "East Pct 3Rd W - Unavail Personn",
    ),
    "North Pct 1St W - Unavail Personnel": ("North Pct 1St W - Unavail Personn",),
    "South Pct 1St W    Unavail Personnel": ("South Pct 1St W    Unavail Personr",),
    "West Pct 2Nd W - Unavail Personnel": ("West Pct 2Nd W - Unavail Personr",),
    "West Pct 3Rd W - Unavail Personnel": (
        "West Pct 3Rd W - Unavail Personr",
        "West Pct 3Rd W    Unavail Personr",
    ),
    "East Pct 3rd W - Charlie": (
        "East Pct 3rd  W - Charlie",
        "East Pct 3Rd W- Charlie",
    ),
    "Southwest Pct 2Nd W - T/Relief Squad": ("Southwest Pct wnd W - T/Relief Sq",),
    "South Pct 3Rd W - T/Relief Squad": ("South Pct 3rd W - T/Relief Squd",),
    "West Pct 3Rd W - Relief Sgts": ("West Pet 3Rd W - Relief Sgts",),
    "West Pct Ops - Cpt": ("West Pct Ops - Cot",),
    "East Pct Ops - Burg/Theft": ("East Pct Ops    Burg/Theft",),
    "North Pct Ops - Burg/Theft": ("North Pct Ops - Burg/Theft North",),
    "South Pct Ops - Burg/Theft": ("South Pet Ops - Burg/Theft",),
    "Southwest Pct Ops - Burg/Theft": ("Southwest. Pet Ops - Burg/Theft",),
    "West Pct Ops - Burg/Theft": (
        "West Pct Ops    Burg/Theft West",
        "West Pct Ops - Burg/Theft West",
    ),
    "East Pct Ops - Cpt": ("East Pet Ops - Cpt",),
    "North Pct Ops": (
        "North Pct Ops    Cpt",
        "North Pet Ops    Cpt",
    ),
    "East Pct Ops - Night Act": ("East Pct Ops -Night Act",),
    "Education & Training Unit": ("Education & Training Section",),
    "Education & Training Unit - Unavail Personnel": (
        "Education & Training Unit - Unavai",
    ),
    "Emergency Management - Coordinators": (
        "Emergency Management - Coordina",
        "Emergency Management - Coordinator~",
    ),
    "Emergency Management - Deputy Director": (
        "Emergency Management - Deputy D",
        "Emergency Management - Deputy Dire~",
    ),
    "Emergency Management - Staff Assistant": (
        "Emergency Management - Staff Ass",
        "Emergency Management - Staff Assis~",
    ),
    "Emergency Management Unit": (
        "Emergency Management Section",
        "Emergency Management Section -",
    ),
    "Emergency Mgmnt - Education And Outreach": (
        "Emergency Mgmnt - Education And",
        "Emergency Mgmnt - Education And Ou~",
    ),
    "Parking Enforcement Unit - Administration": (
        "Parking Enforcement Unit - Adminis",
        "Parking Enforcement Unit - Adminis~",
    ),
    "Evidence - Firearms Specialist Detail": (
        "Evidence - Firearms Specialist Deta",
        "Evidence - Firearms Specialist Det~",
    ),
    "Evidence Unit": ("Evidence Unit.",),
    "Field Support Bureau - Administration": ("Field Support Bureau - Administrat",),
    "Fleet Control Unit": ("Fleet Control", "Fleet Control Squad"),
    "Force Investigations - Administration": ("Force Investigations - Administrat~",),
    "General Investigations Unit - Administration": (
        "General Investigations - Administration Squad",
        "General Investigations Unit - Admii",
        "General Investigations Unit - Admil",
    ),
    "Special Investigations Unit - Administration": (
        "Special Investigations Section - Administration",
        "Special Investigations Unit - Admini",
        "Special Investigations Unit - Admi~",
    ),
    "Force Review Section - Administration": (
        "Force Review Section - Administrati",
        "Force Review Section - Administrat~",
    ),
    "Forensic Digital Imaging - Administration": (
        "Forensic Digital Imaging - Adminisi",
    ),
    "Forensic Support Services - Administration": (
        "Forensic Support Services - Admir",
    ),
    "Forensics - Crime Scene Investigations": (
        "Forensics - Crime Scene Investigati",
        "Forensics - Crime Scene Investigat~",
    ),
    "Fraud, Forgery And Financial Exploitation": (
        "Fraud, Forgery And Financial Expk",
        "Fraud, Forgery And Financial Explo",
        "Fraud, Forgery And Financial Explo~",
        "Fraud, Forgery And Financial Explc",
    ),
    "Special Investigations Section - Administration": (
        "Special Investigations Section - Ad",
    ),
    "High Risk Victims Section - Administration": (
        "High Risk Victims Section - Admini",
        "High Risk Victims Section - Admini~",
    ),
    "Hls - Cbrne Support": ("Hls - Cbrne Support Detail",),
    "Hls - Special Event Planning/Spoc": (
        "Hls - Special Event Planning/Spoc (",
        "Hls - Special Event Planning/Spoc ~",
    ),
    "Hls - Special Ops Bureau - Administration": (
        "Hls - Special Ops Bureau - Adminis",
    ),
    "Special Ops Bureau - Administration": (
        "Special Ops Bureau - Administratic",
        "Special Ops Bureau - Administratio~",
    ),
    "Homeland Security Section - Administration": (
        "Homeland Security Section - Admii",
        "Homeland Security Section - Admin",
        "Homeland Security Section - Admini~",
    ),
    "Homeland Security Bureau - Administration": (
        "Homeland Security Bureau - Adminis~",
    ),
    "Homicide & Assault Unit - Administration": (
        "Homicide & Assault Unit - Adminis1",
        "Homicide & Assault Unit - Administ",
        "Homicide & Assault Unit - Administ~",
    ),
    "Homicide - Violent Crimes Advocates": (
        "Homicide - Violent Crimes Advocate",
        "Homicide - Violent Crimes Advocate~",
    ),
    "Violent Crimes Advocates": ("Violent Crime Advocates",),
    "Homicide Squad B": ("Hornicide Squad B",),
    "Hr - Department Unavailable Person": ("Hr - Department Unavailable Person~",),
    "Hr - Employment Services Unit - Administration": (
        "Hr - Employment Services Unit - Ad",
        "Hr - Employment Services Unit - Ad~",
    ),
    "Hr - Human Resources - Administration": (
        "Hr - Human Resources - Administra",
        "Hr - Human Resources - Administrat~",
        "Hr - Human Resources Section - Administration",
    ),
    "Hr - Human Resources - Dept Unavail Personnel": (
        "Human Resources - Dept Unavail P",
    ),
    "Hr - Human Resources - Special Projects": ("Hr - Human Resources - Special Pr",),
    "Hr - Personnel Records And Benefits": (
        "Hr - Personnel Records And Benefit",
        "Hr - Personnel Records And Benefit~",
    ),
    "Hr - Recruitment": ("Recruitment",),
    "Icac - Internet Crimes Against Child": ("Icac - Internet Crimes Against Chi~",),
    "Icac Investigations": (
        "Icac Investigations.",
        "lcac Investigations",
    ),
    "Information Technology Section - Administration": (
        "Information Technology Section",
        "Information Technology Section -",
        "Information Technology Section - Ad",
    ),
    "Intell - Technical Assistance Squad": (
        "Intel! - Technical Assistance",
        "Intell - Technical Assistance",
        "Intell - Technical Assistance Squa~",
    ),
    "Inv Supp - Technical Assistance Squad": ("Inv Supp - Technical Assistance Sq~",),
    "Intell - Administration And Analysis": ("Intell - Administration And Analys~",),
    "Inv Supp - Administration And Analysis": ("Inv Supp - Administration And Anal~",),
    "Inv Supp - Fusion Center Assignment": ("Inv Supp - Fusion Center Assignmen~",),
    "Inv Supp - Gang Intelligence Detail": ("Inv Supp - Gang Intelligence Detai~",),
    "Intell - Special Investigations And Assignments Squad": (
        "Intell - Special Investigations And A",
        "Intell - Special Investigations An~",
    ),
    "Inv Supp - Special Investigations": ("Inv Supp - Special Investigations ~",),
    "Intell - Tactical Crime Analysis Squad": (
        "Intell - Tactical Crime Analysis S~",
        "Tactical Crime Analysis Squad",
    ),
    "Inv Supp - Tactical Crime Analysis": ("Inv Supp - Tactical Crime Analysis~",),
    "Investigations Bureau - Administration": (
        "Investigations Bureau - Administrati",
        "Investigations Bureau - Administra~",
    ),
    "Its - 911 Technical Support - Squad A": ("Its - 911 Technical Support - Squad",),
    "Its - Applications - Squad B": ("Its - Applications - Suqd B",),
    "Its - Applications Development - Squad A": (
        "Its - Applications Development",
        "Its - Applications Development - Squ",
    ),
    "Its - Special Projects - Squad A (Sit)": (
        "Its - Special Projects - Squad A (Sit",
    ),
    "Its - Special Projects - Squad C (Sit)": (
        "Its - Special Projects - Squad C (Sit",
    ),
    "Legal - Senior Police Counsel - Administration": (
        "Legal - Senior Police Counsel - Adm",
        "Legal - Senior Police Counsel - Ad~",
    ),
    "Legal - Support And Public Disclosure Unit": (
        "Legal - Support And Public Disclosu",
        "Legal - Support And Public Disclos~",
    ),
    "Metropolitan Section - Administration": (
        "Metropolitan Section - Administratio",
        "Metropolitan Section - Administrat~",
    ),
    "Metropolitan Section - Force Review": ("Metropolitan Section - Force Revie~",),
    "Motorcycle Unit - T4 Squad": ("Motorcycle Unit -14 Squad",),
    "Narc - Proactive Squad A": ("Proactive Squad A",),
    "Narc - Proactive Squad B": ("Proactive Squad B",),
    "Narc - Proactive Squad C": ("Proactive Squad C",),
    "Neighborhood Policing - Deployment Detail": ("Neighborhood Policing - Deployme",),
    "North Pct 1St W - Lincoln": ("North Pct 1St VV    Lincoln",),
    "North Pct 1St W - John": ("North Pct 1St W    John",),
    "North Pct 1St W - Union": ("North Pct 1St W    Union",),
    "North Pct 2Nd W - Lincoln": (
        "North Pct 2Nd W    Lincoln",
        "North Pet 2Nd W - Lincoln",
    ),
    "North Pct 3Rd W - Lincoln": (
        "North Pct 3Rd W    Lincoln",
        "North Pet 3Rd W - Lincoln",
    ),
    "North Pct 1St W - Nora": ("North Pct 1St VV - Nora",),
    "North Pct 1St W - Boy": ("North Pct 1St W    Boy",),
    "North Pct 3Rd W - Boy": ("North Pct 3Rd W Boy",),
    "North Pct 3Rd W - John": (
        "North Pct 3Rd :W - John",
        "North Pct 3Rd W -'John",
    ),
    "North Pct 2Nd W - Union": ("North Pet 2Nd W - Union",),
    "North Pct 1St W - B/N Relief (John)": ("North Pct 1St W - B/N Relief (John~",),
    "Southwest Pct 1St W - Relief Sgts": ("Southwest Pct 1St .W - Relief Sgts",),
    "Southwest Pct 1St W - William": ("Southwest Pct 1St W -. William",),
    "West Pct 2Nd W - Relief Sgts": (
        "West Pct 2Nd W - Relief Sgts.",
        "West Pet 2Nd W -Relief Sgts",
    ),
    "North Pct 2Nd W - John": ("North Pet 2Nd VV - John.",),
    "South Pct 3Rd W - Sam": (
        "South Pct 3Rd W Sam",
        "South Pct 3Rd W-` Sam",
    ),
    "South Pct 3Rd W - Ocean": (
        "South Pct 3Rd W Ocean",
        "South Pct 3Rd W- Ocean",
        "South Pct 3Rd VV - Ocean",
    ),
    "North Pct Ops - Act Night": ("North Pet Ops - Act Night",),
    "West Pct Ops - Act Night": ("West Pct Ops    Act Night",),
    "Opa - Communications And Outreach": ("Opa - Communications And Outreac",),
    "Opa - Compliance, Policy And Research": (
        "Opa - Compliance, Policy And Rese",
        "Opa - Compliance, Policy And Resea~",
    ),
    "Opa - Internal Investigations Intake - Squad A": (
        "Opa - Internal Investigations Intake Unit",
    ),
    "Opa - Investigations - A - Communications": (
        "Opa - Investigations - A - Communi~",
    ),
    "Opa - Investigations - B - Communications": (
        "Opa - Investigations - B - Communi~",
    ),
    "Opa - Office Of Police Accountability": (
        "Opa - Office Of Police Accountabilit",
        "Opa - Office Of Police Accountabil~",
    ),
    "Opa - Operations, Compliance, Outreach": (
        "Opa - Operations, Compliance, Out",
        "Opa - Operations, Compliance, Outr~",
    ),
    "Patrol Operations Bureau - Administration": (
        "Patrol Operations Bureau - Adminis",
        "Patrol Operations Bureau - Adminis~",
    ),
    "Parking Enforcement - Training Squad": (
        "Parking Enforcement - Training Squ",
        "Parking Enforcement - Training Squ~",
    ),
    "Patrol Operations Bureau": ("Patrol Operations  Bureau",),
    "Patrol Operations - Duty Captain": ("Patrol Operations - Duty Captains",),
    "Traf - Pm Enforcement": ("Pm Enforcement",),
    "Professional Standards Bureau - Administration": (
        "Professional Standards Bureau - Ad",
        "Professional Standards Bureau - Ad~",
    ),
    "Public Affairs Squad": (
        "Public Affairs",
        "Public Affairs Unit",
    ),
    "Puget Sound Violent Crimes Task Force": (
        "Puget Sound Violent Crimes Task",
        "Puget Sound Violent Crimes Task Force (Psvctf)",
    ),
    "Quartermaster Squad": ("Quartermaster",),
    "Records - Warehouse": ("Records - Warehouser",),
    "Robbery, Fugitive & Gang Unit - Administration": (
        "Robbery, Fugitive & Gang Unit - Ac",
        "Robbery, Fugitive & Gang Unit - Adm",
        "Robbery, Fugitive & Gang Unit - Ad~",
        "Robbery, Fugitive & Gvr Unit - Adm~",
    ),
    "Sau - Sex Offender Detail": ("Sex Offender Detail",),
    "Sau - Sexual Aslt & Child Abuse Unit - Administration": (
        "Sau - Sexual Aslt & Child Abuse Un",
        "Sau - Sexual Aslt & Child Abuse Un~",
        "Sau - Sexual Assault And Child Abuse Unit",
    ),
    "Sau - Special Crimes Advocates": (
        "Special Crimes Advocates",
        "Special'Crimes Advocates",
    ),
    "South Pct 1St W - Ocean": (
        "South Pct 1St W Ocean",
        "South Pet 1St W - Ocean",
    ),
    "South Pct 1St W - Sam": (
        "South Pet 1St W - Sam",
        "South Pet 1St W Sam",
    ),
    "South Pct 1St W - Robert": ("South Pet 1St W - Robert",),
    "South Pct 2Nd W - Robert": (
        "South Pct 2Nd ,W, - Robert",
        "South Pet 2Nd W - Robert",
    ),
    "South Pct 3Rd W - Robert": (
        "South Pct 3Rd W -:Robert",
        "South Pet 3Rd W - Robert",
    ),
    "Southwest Pct 3Rd W - Frank": ("Southwest Pet 3Rd W - Frank",),
    "Southwest Pct 2Nd W - Frank": (
        "Southwest Pet 2Nd W - Frank",
        "Southwest Pet 2Nd W -frank",
    ),
    "Southwest Pct 1St W - Frank": ("Southwest Pot 1St W _-Frank",),
    "Southwest Pct 2Nd W - William": (
        "Southwest Pct 2Nd W William",
        "Southwest Pot 2Nd W - William",
    ),
    "Southwest Pct 3Rd W - William": (
        "Southwest Pct 3Rd W William",
        "Southwest Pot 3Rd W - William",
    ),
    "Southwest Pct Ops - Night Act": ("Southwest Pat Ops - Night Act",),
    "Special Assignments - Unavail Personnel": ("Special Assignments - Unavail Per",),
    "Special Assignments Unit - Administration": (
        "Special Assignments Unit - Admini",
        "Special Investigations Unit - Admi~",
    ),
    "Special Services Section - Administration": (
        "Special Services Section - Adminis~",
    ),
    "Special Victim Crimes Section - Administration": (
        "Special Victim Crimes Section - Ad",
        "Special Victim Crimes Section - Ad~",
    ),
    "Swat - Night Squad 2": ("Swat    Night Squad 2",),
    "Swat - Day Squad 2": ("Swat-Day Squad 2",),
    "Ten Print - Day Shift": ("Tenprint - Day Shift",),
    "Ten Print - Graveyard Shift": ("Tenprint - Graveyard Shift",),
    "Ten Print - Swing Shift": (
        "Ten Print-swing Shift",
        "Tenprint - Swing Shift",
    ),
    "Traf - Photo Enforcement Detail": ("Traf - Photo Enforcement",),
    "Traf - Collision Investigation": ("Traffic Collision Investigation",),
    "Traf - Motorcycle - T2 Squad": ("Traf - Motorcycle Unit - T2 Squad",),
    "Traf - Motorcycle - T3 Squad": ("Traf - Motorcycle Unit - T3 Squad",),
    "Traf - Motorcycle - T4 Squad": ("Traf - Motorcycle Unit - T4 Squad",),
    "Training - Field Training Squad - Administration": (
        "Training - Field Training Squad - Adm",
        "Training - Field Training Squad - ~",
    ),
    "Training - Learning Management System": (
        "Training - Learning Management Sy",
        "Training - Learning Management Sys~",
    ),
    "Training And Education Section - Administration": (
        "Training And Education Section - Ad",
        "Training And Education Section - A~",
    ),
    "Violent Crime Advocates": ("Violent Crimes Advocates",),
    "Violent Crimes Section - Administration": (
        "Violent Crimes Section - Administra",
        "Violent Crimes Section - Administr~",
    ),
    "West Pct 2Nd W - David": (
        "West Pet 2Nd W - David",
        "West Pct 2Nd \\/V - David",
    ),
    "West Pct 2Nd W - King": ("West Pet 2Nd W - King",),
    "West Pct 3Rd W - Mary": ("West Pet 3Rd W - Mary",),
    "West Pct 1St W - King": ("West Pet 1St W - King",),
    "West Pct 3Rd W - King": ("West Pet 3Rd W - King",),
    "West Pct 3Rd W - Queen": ("West Pet 3Rd W - Queen",),
    "West Pct 2Nd W - Queen": (
        "West Pct 2Nd VV - Queen",
        "West Pct. 2Nd W - Queen",
    ),
}
