update officers set race = 'Not Sure' where race = 'Not Specified';
update officers set race = 'ASIAN PACIFIC ISLANDER' where race = 'Asian/Pacific Islander';
update officers set race = 'BLACK' where race = 'Black or African American';
update officers set race = 'NATIVE AMERICAN' where race = 'American Indian/Alaska Native';
update officers set race = 'HISPANIC' where race = 'Hispanic';
update officers set race = 'Other' where race = 'Not Applicable (Non-U.S.)';
update officers set race = 'WHITE' where race = 'White';
update officers set race = 'BLACK' where unique_internal_identifier = 'J486';
update officers set race = 'BLACK' where unique_internal_identifier = 'I752';
update officers set race = 'BLACK' where unique_internal_identifier = 'I234';
update officers set race = 'WHITE' where unique_internal_identifier = 'I536';
update officers set race = 'WHITE' where unique_internal_identifier = 'H825';
update officers set race = 'BLACK' where unique_internal_identifier = 'I458';
update officers set race = 'BLACK' where unique_internal_identifier = 'J039';
update officers set race = 'BLACK' where unique_internal_identifier = 'G874';
update officers set race = 'WHITE' where unique_internal_identifier = 'I544';
update officers set race = 'BLACK' where unique_internal_identifier = 'F712';
update officers set race = 'WHITE' where unique_internal_identifier = 'I850';
update officers set race = 'BLACK' where unique_internal_identifier = 'I855';
update officers set race = 'BLACK' where unique_internal_identifier = 'J107';
update officers set race = 'BLACK' where unique_internal_identifier = 'I725';
update officers set race = 'BLACK' where unique_internal_identifier = 'H832';
update officers set race = 'WHITE' where unique_internal_identifier = 'G098';
update officers set race = 'WHITE' where unique_internal_identifier = 'J843';
update officers set race = 'WHITE' where unique_internal_identifier = 'G194';
update officers set race = 'WHITE' where unique_internal_identifier = 'I995';
update officers set race = 'WHITE' where unique_internal_identifier = 'I831';
update officers set race = 'ASIAN PACIFIC ISLANDER' where unique_internal_identifier = 'G752';
update officers set race = 'WHITE' where unique_internal_identifier = 'F969';
update officers set race = 'WHITE' where unique_internal_identifier = 'H074';
update officers set race = 'WHITE' where unique_internal_identifier = 'G707';
update officers set race = 'WHITE' where unique_internal_identifier = 'I899';
update officers set race = 'WHITE' where unique_internal_identifier = 'H388';
