# User Constants
AC_USER_EMAIL = "raq929@example.org"
AC_USER_PASSWORD = "horse"
ADMIN_USER_EMAIL = "test@example.org"
ADMIN_USER_PASSWORD = "testtest"
GENERAL_USER_EMAIL = "jen@example.org"
GENERAL_USER_PASSWORD = "dog"
DISABLED_USER_EMAIL = "may@example.org"
DISABLED_USER_PASSWORD = "yam"
MOD_DISABLED_USER_EMAIL = "sam@example.org"
MOD_DISABLED_USER_PASSWORD = "the yam"
UNCONFIRMED_USER_EMAIL = "freddy@example.org"
UNCONFIRMED_USER_PASSWORD = "dog"
