# File Mode Constants
FILE_MODE_WRITE = "w"

# User Constants
AC_USER_EMAIL = "raq929@example.org"
AC_USER_PASSWORD = "horse"
AC_USER_USERNAME = "test_ac"
ADMIN_USER_EMAIL = "test@example.org"
ADMIN_USER_PASSWORD = "testtest"
ADMIN_USER_USER_NAME = "test_admin"
GENERAL_USER_EMAIL = "jen@example.org"
GENERAL_USER_PASSWORD = "dog"
GENERAL_USER_USERNAME = "test_user"
DISABLED_USER_EMAIL = "may@example.org"
DISABLED_USER_PASSWORD = "yam"
DISABLED_USER_USERNAME = "may"
MOD_DISABLED_USER_EMAIL = "sam@example.org"
MOD_DISABLED_USER_PASSWORD = "the yam"
MOD_DISABLED_USER_USERNAME = "sam"
UNCONFIRMED_USER_EMAIL = "freddy@example.org"
UNCONFIRMED_USER_PASSWORD = "dog"
UNCONFIRMED_USER_USERNAME = "b_meson"
