name: Test Coverage

on:
  pull_request:
    branches:
    - develop
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get-coverage:
    runs-on: ubuntu-latest
    env:
      FLASK_APP: OpenOversight.app
    strategy:
      matrix:
        python-version: [ "3.8", "3.9" ]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run tests
      - run: |
          PYTHON_VERSION=${{ matrix.python-version }} make test_with_version
          flake8 --ignore=E501,E722,W504,W503
          coveralls
