name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches:
    - develop
    - main
  pull_request:
    branches:
    - develop
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    env:
      FLASK_APP: OpenOversight.app
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Run tests
        run: PYTHON_VERSION=${{ matrix.python-version }} make test_with_version
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: pip install pre-commit
      - name: Run pre-commits
        run: pre-commit run --all-files
