name: Test Coverage
on:
  pull_request:
    branches:
    - develop
    - main
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FLASK_APP: OpenOversight.app
    steps:
      - uses: actions/checkout@v3
        with:
          python-version: "3.9"
      - name: Run tests
        run: |
          PYTHON_VERSION=${{ matrix.python-version }} make test_with_version
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit Test
  coveralls_finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
